name := "Twitter Sparse Download"
version := "1.0"
scalaVersion := "2.10.6"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.6.1"
resolvers += "Akka Repository" at "http://repo.akka.io/releases/"
