name := "Twitter Download"
version := "1.0"
scalaVersion := "2.10.6"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.6.1"
libraryDependencies += "org.scalaj" %% "scalaj-http" % "2.3.0"
resolvers += "Akka Repository" at "http://repo.akka.io/releases/"
